const CART_KEY="testt-cart";
const products=[
{id:1,name:"Obsidian Watch",price:189,tag:"Accessories",icon:"◉",desc:"Minimal automatic watch with a brushed steel case and deep black dial."},
{id:2,name:"Noir Headphones",price:149,tag:"Audio",icon:"◖◗",desc:"Wireless over-ear headphones designed around focused listening."},
{id:3,name:"Atlas Pack",price:119,tag:"Carry",icon:"▣",desc:"Structured everyday backpack with a clean silhouette and durable build."},
{id:4,name:"Mono Lamp",price:89,tag:"Home",icon:"◒",desc:"Architectural desk lamp with a warm, directional light."},
{id:5,name:"Studio Camera",price:299,tag:"Tech",icon:"▰",desc:"Compact creator camera concept for everyday visual work."},
{id:6,name:"Field Bottle",price:39,tag:"Everyday",icon:"◫",desc:"Double-wall steel bottle with a restrained matte finish."},
{id:7,name:"Arc Keyboard",price:129,tag:"Tech",icon:"⌨",desc:"Low-profile mechanical keyboard with a precise, quiet feel."},
{id:8,name:"Vector Mouse",price:69,tag:"Tech",icon:"◌",desc:"Ergonomic wireless mouse with a clean professional silhouette."},
{id:9,name:"Slate Wallet",price:59,tag:"Accessories",icon:"▤",desc:"Slim everyday wallet cut for essential cards and cash."},
{id:10,name:"Form Chair",price:349,tag:"Home",icon:"⌂",desc:"Sculptural lounge chair designed for long, comfortable sessions."},
{id:11,name:"Signal Speaker",price:179,tag:"Audio",icon:"◒",desc:"Compact wireless speaker with a balanced room-filling profile."},
{id:12,name:"Core Hoodie",price:79,tag:"Everyday",icon:"◇",desc:"Heavyweight cotton hoodie with a clean, relaxed fit."},
{id:13,name:"Grid Notebook",price:24,tag:"Everyday",icon:"▧",desc:"Hardcover notebook built for ideas, plans, and daily notes."},
{id:14,name:"Halo Desk Set",price:109,tag:"Home",icon:"○",desc:"Minimal desk accessories designed to work as one visual system."},
{id:15,name:"Pulse Earbuds",price:99,tag:"Audio",icon:"◍",desc:"Compact wireless earbuds focused on clarity and everyday comfort."},
{id:16,name:"Frame Sunglasses",price:74,tag:"Accessories",icon:"◎",desc:"Sharp acetate frames with a restrained, timeless profile."},
{id:17,name:"Terra Mug",price:32,tag:"Home",icon:"∪",desc:"Hand-finished ceramic mug with a tactile matte surface."},
{id:18,name:"Core SSD",price:139,tag:"Tech",icon:"▭",desc:"Portable solid-state storage for creators and everyday workflows."}
];
function getCart(){try{return JSON.parse(localStorage.getItem(CART_KEY))||[]}catch{return[]}}
function saveCart(c){localStorage.setItem(CART_KEY,JSON.stringify(c));updateCount()}
function updateCount(){const n=getCart().reduce((s,x)=>s+x.qty,0);document.querySelectorAll("[data-cart-count]").forEach(e=>e.textContent=n)}
function money(n){return "$"+n.toLocaleString()}
function productCard(p){return '<article class="card"><a href="product.html?id='+p.id+'"><div class="product-image" aria-hidden="true">'+p.icon+'</div><div class="product-body"><span class="tag">'+p.tag+'</span><h3>'+p.name+'</h3><p class="muted">'+p.desc+'</p><div class="price">'+money(p.price)+'</div></div></a></article>'}
function renderProducts(){const root=document.querySelector("#products");if(!root)return;const search=(document.querySelector("#product-search")?.value||"").trim().toLowerCase();const category=document.querySelector(".filter.active")?.dataset.category||"All";const sort=document.querySelector("#product-sort")?.value||"featured";let list=products.filter(p=>(category==="All"||p.tag===category)&&(!search||(p.name+" "+p.desc+" "+p.tag).toLowerCase().includes(search)));if(sort==="price-low")list.sort((a,b)=>a.price-b.price);if(sort==="price-high")list.sort((a,b)=>b.price-a.price);if(sort==="name")list.sort((a,b)=>a.name.localeCompare(b.name));root.innerHTML=list.length?list.map(productCard).join(""):'<div class="empty">No products match your search.</div>';const result=document.querySelector("#result-count");if(result)result.textContent=list.length+" products"}
document.addEventListener("DOMContentLoaded",()=>{updateCount();const featured=document.querySelector("#featured");if(featured)featured.innerHTML=products.slice(0,6).map(productCard).join("");if(document.querySelector("#products")){document.querySelectorAll(".filter").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderProducts()}));document.querySelector("#product-search")?.addEventListener("input",renderProducts);document.querySelector("#product-sort")?.addEventListener("change",renderProducts);renderProducts()}const detail=document.querySelector("#detail");if(detail){const id=Number(new URLSearchParams(location.search).get("id"))||1,p=products.find(x=>x.id===id)||products[0];document.title=p.name+" — Testt";detail.innerHTML='<div class="detail-image" aria-label="'+p.name+'">'+p.icon+'</div><div><span class="tag">'+p.tag+'</span><h1>'+p.name+'</h1><p class="muted">'+p.desc+'</p><div class="detail-price">'+money(p.price)+'</div><ul><li>Premium everyday construction</li><li>Designed with a minimal aesthetic</li><li>30-day return policy</li></ul><div class="qty"><button id="minus" aria-label="Decrease quantity">−</button><input id="qty" value="1" aria-label="Quantity" readonly><button id="plus" aria-label="Increase quantity">+</button></div><button class="btn btn-primary" id="add-btn">Add to cart</button></div>';let q=1;document.querySelector("#minus").onclick=()=>{q=Math.max(1,q-1);document.querySelector("#qty").value=q};document.querySelector("#plus").onclick=()=>{q++;document.querySelector("#qty").value=q};document.querySelector("#add-btn").onclick=()=>{const c=getCart(),item=c.find(x=>x.id===p.id);item?item.qty+=q:c.push({id:p.id,qty:q});saveCart(c);document.querySelector("#add-btn").textContent="Added to cart ✓"}}const cart=document.querySelector("#cart");if(cart){const c=getCart();if(!c.length){cart.innerHTML='<div class="empty">Your cart is empty. <a href="products.html"><u>Browse products</u></a></div>'}else{cart.innerHTML=c.map(x=>{const p=products.find(y=>y.id===x.id);if(!p)return"";return '<div class="cart-row"><div><strong>'+p.name+'</strong><div class="muted">'+money(p.price)+' × '+x.qty+'</div></div><div class="price">'+money(p.price*x.qty)+'</div><button class="btn btn-secondary" data-remove="'+p.id+'">Remove</button></div>'}).join("");const total=c.reduce((s,x)=>{const p=products.find(p=>p.id===x.id);return s+(p?p.price*x.qty:0)},0);cart.insertAdjacentHTML("beforeend",'<div class="cart-total"><span>Total</span><span>'+money(total)+'</span></div><button class="btn btn-primary" id="checkout">Checkout</button>');document.querySelector("#checkout").onclick=()=>alert("Demo checkout — connect your payment backend here.");cart.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{saveCart(c.filter(x=>x.id!==Number(b.dataset.remove)));location.reload()})}}});