const CART_KEY="testt-cart";
const fallbackProducts=[
{id:1,name:"Obsidian Watch",price:189,category:"Accessories",icon:"◉",description:"Minimal automatic watch with a brushed steel case and deep black dial."},
{id:2,name:"Noir Headphones",price:149,category:"Audio",icon:"◖◗",description:"Wireless over-ear headphones designed around focused listening."},
{id:3,name:"Atlas Pack",price:119,category:"Everyday",icon:"▣",description:"Structured everyday backpack with a clean silhouette and durable build."},
{id:4,name:"Mono Lamp",price:89,category:"Home",icon:"◒",description:"Architectural desk lamp with a warm, directional light."},
{id:5,name:"Studio Camera",price:299,category:"Tech",icon:"▰",description:"Compact creator camera concept for everyday visual work."},
{id:6,name:"Field Bottle",price:39,category:"Everyday",icon:"◫",description:"Double-wall steel bottle with a restrained matte finish."},
{id:7,name:"Arc Keyboard",price:129,category:"Tech",icon:"⌨",description:"Low-profile mechanical keyboard with a precise, quiet feel."},
{id:8,name:"Vector Mouse",price:69,category:"Tech",icon:"◌",description:"Ergonomic wireless mouse with a clean professional silhouette."},
{id:9,name:"Slate Wallet",price:59,category:"Accessories",icon:"▤",description:"Slim everyday wallet cut for essential cards and cash."},
{id:10,name:"Form Chair",price:349,category:"Home",icon:"⌂",description:"Sculptural lounge chair designed for long, comfortable sessions."},
{id:11,name:"Signal Speaker",price:179,category:"Audio",icon:"◒",description:"Compact wireless speaker with a balanced room-filling profile."},
{id:12,name:"Core Hoodie",price:79,category:"Everyday",icon:"◇",description:"Heavyweight cotton hoodie with a clean, relaxed fit."},
{id:13,name:"Grid Notebook",price:24,category:"Everyday",icon:"▧",description:"Hardcover notebook built for ideas, plans, and daily notes."},
{id:14,name:"Halo Desk Set",price:109,category:"Home",icon:"○",description:"Minimal desk accessories designed to work as one visual system."},
{id:15,name:"Pulse Earbuds",price:99,category:"Audio",icon:"◍",description:"Compact wireless earbuds focused on clarity and everyday comfort."},
{id:16,name:"Frame Sunglasses",price:74,category:"Accessories",icon:"◎",description:"Sharp acetate frames with a restrained, timeless profile."},
{id:17,name:"Terra Mug",price:32,category:"Home",icon:"∪",description:"Hand-finished ceramic mug with a tactile matte surface."},
{id:18,name:"Core SSD",price:139,category:"Tech",icon:"▭",description:"Portable solid-state storage for creators and everyday workflows."}
];
let products=[...fallbackProducts];
const getCart=()=>{try{return JSON.parse(localStorage.getItem(CART_KEY))||[]}catch{return[]}};
const saveCart=c=>{localStorage.setItem(CART_KEY,JSON.stringify(c));updateCount()};
const updateCount=()=>{const n=getCart().reduce((s,x)=>s+x.qty,0);document.querySelectorAll("[data-cart-count]").forEach(e=>e.textContent=n)};
const money=n=>"$"+Number(n).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
function productCard(p){return '<article class="card"><a href="product.html?id='+p.id+'"><div class="product-image" aria-hidden="true">'+p.icon+'</div><div class="product-body"><span class="tag">'+p.category+'</span><h3>'+p.name+'</h3><p class="muted">'+p.description+'</p><div class="price">'+money(p.price)+'</div></div></a></article>'}
async function loadProducts(){const{data,error}=await window.testtSupabase.from("products").select("id,name,description,price,category,icon").eq("active",true).order("id");if(error)console.warn("Supabase products unavailable:",error.message);if(data?.length)products=data.map(p=>({...p,price:Number(p.price),description:p.description||""}));return products}
function renderProducts(){const root=document.querySelector("#products");if(!root)return;const search=(document.querySelector("#product-search")?.value||"").trim().toLowerCase();const category=document.querySelector(".filter.active")?.dataset.category||"All";const sort=document.querySelector("#product-sort")?.value||"featured";let list=products.filter(p=>(category==="All"||p.category===category)&&(!search||(p.name+" "+p.description+" "+p.category).toLowerCase().includes(search)));if(sort==="price-low")list.sort((a,b)=>a.price-b.price);if(sort==="price-high")list.sort((a,b)=>b.price-a.price);if(sort==="name")list.sort((a,b)=>a.name.localeCompare(b.name));root.innerHTML=list.length?list.map(productCard).join(""):'<div class="empty">No products match your search.</div>';const result=document.querySelector("#result-count");if(result)result.textContent=list.length+" products"}
function bindProductFilters(){document.querySelectorAll(".filter").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderProducts()}));document.querySelector("#product-search")?.addEventListener("input",renderProducts);document.querySelector("#product-sort")?.addEventListener("change",renderProducts)}
async function renderDetail(){const detail=document.querySelector("#detail");if(!detail)return;const id=Number(new URLSearchParams(location.search).get("id"))||1;const p=products.find(x=>x.id===id)||products[0];if(!p){detail.innerHTML='<div class="empty">Product not found.</div>';return}document.title=p.name+" — Testt";detail.innerHTML='<div class="detail-image" aria-label="'+p.name+'">'+p.icon+'</div><div><span class="tag">'+p.category+'</span><h1>'+p.name+'</h1><p class="muted">'+p.description+'</p><div class="detail-price">'+money(p.price)+'</div><ul><li>Premium everyday construction</li><li>Designed with a minimal aesthetic</li><li>30-day return policy</li></ul><div class="qty"><button id="minus" aria-label="Decrease quantity">−</button><input id="qty" value="1" aria-label="Quantity" readonly><button id="plus" aria-label="Increase quantity">+</button></div><button class="btn btn-primary" id="add-btn">Add to cart</button></div>';let q=1;document.querySelector("#minus").onclick=()=>{q=Math.max(1,q-1);document.querySelector("#qty").value=q};document.querySelector("#plus").onclick=()=>{q=Math.min(99,q+1);document.querySelector("#qty").value=q};document.querySelector("#add-btn").onclick=()=>{const c=getCart(),item=c.find(x=>x.id===p.id);item?item.qty=Math.min(99,item.qty+q):c.push({id:p.id,qty:q});saveCart(c);document.querySelector("#add-btn").textContent="Added to cart ✓"}}
async function submitOrder(){const form=document.querySelector("#checkout-form");if(!form)return;const button=form.querySelector("button[type=submit]");button.disabled=true;button.textContent="Processing…";const fd=new FormData(form);const{data,error}=await window.testtSupabase.rpc("place_order",{p_customer_name:String(fd.get("name")||""),p_customer_email:String(fd.get("email")||""),p_items:getCart()});if(error){alert("Could not place the order: "+error.message);button.disabled=false;button.textContent="Place order";return}localStorage.removeItem(CART_KEY);updateCount();form.outerHTML='<div class="success"><strong>Order received.</strong><p class="muted">Your order #'+String(data).slice(0,8)+' has been created successfully.</p><a class="btn btn-primary" href="products.html">Continue shopping</a></div>'}
function renderCart(){const cart=document.querySelector("#cart");if(!cart)return;const c=getCart();if(!c.length){cart.innerHTML='<div class="empty">Your cart is empty. <a href="products.html"><u>Browse products</u></a></div>';return}const valid=c.map(x=>({...x,product:products.find(p=>p.id===x.id)})).filter(x=>x.product);const total=valid.reduce((s,x)=>s+x.product.price*x.qty,0);cart.innerHTML=valid.map(x=>'<div class="cart-row"><div><strong>'+x.product.name+'</strong><div class="muted">'+money(x.product.price)+' × '+x.qty+'</div></div><div class="price">'+money(x.product.price*x.qty)+'</div><button class="btn btn-secondary" data-remove="'+x.product.id+'">Remove</button></div>').join("")+'<div class="cart-total"><span>Total</span><span>'+money(total)+'</span></div><form id="checkout-form" class="contact-form"><h2>Checkout</h2><p class="muted">Your order will be stored securely in the Testt database.</p><div class="field"><label for="checkout-name">Name</label><input id="checkout-name" name="name" required maxlength="120" placeholder="Your name"></div><div class="field"><label for="checkout-email">Email</label><input id="checkout-email" name="email" type="email" required maxlength="320" placeholder="you@example.com"></div><button class="btn btn-primary" type="submit">Place order</button></form>';cart.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{saveCart(c.filter(x=>x.id!==Number(b.dataset.remove)));renderCart()});document.querySelector("#checkout-form").addEventListener("submit",e=>{e.preventDefault();submitOrder()})}
async function submitContact(){const form=document.querySelector("#contact-form");if(!form)return;const button=form.querySelector("button[type=submit]");button.disabled=true;button.textContent="Sending…";const fd=new FormData(form);const{error}=await window.testtSupabase.from("contact_messages").insert({name:String(fd.get("name")||"").trim(),email:String(fd.get("email")||"").trim(),message:String(fd.get("message")||"").trim()});if(error){alert("Could not send your message: "+error.message);button.disabled=false;button.textContent="Send message";return}form.reset();button.disabled=false;button.textContent="Message sent ✓"}
document.addEventListener("DOMContentLoaded",async()=>{updateCount();await loadProducts();const featured=document.querySelector("#featured");if(featured)featured.innerHTML=products.slice(0,6).map(productCard).join("");if(document.querySelector("#products")){bindProductFilters();renderProducts()}await renderDetail();renderCart();document.querySelector("#contact-form")?.addEventListener("submit",e=>{e.preventDefault();submitContact()})});