revoke all on function public.place_order(text,text,jsonb) from anon,authenticated,public;
revoke all on function public.rls_auto_enable() from anon,authenticated,public;
drop policy if exists "No direct public access to orders" on public.orders;
drop policy if exists "No direct public access to order items" on public.order_items;
-- RLS policies intentionally use (select auth.jwt()) so the JWT is evaluated once per statement rather than per row.
drop policy if exists "Admins can read own admin record" on public.admins;
create policy "Admins can read own admin record" on public.admins for select to authenticated using(lower(email)=lower(coalesce((select auth.jwt()->>'email'),'')));
drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products" on public.products for select to anon,authenticated using(active=true or exists(select 1 from public.admins a where lower(a.email)=lower(coalesce((select auth.jwt()->>'email'),''))));
drop policy if exists "Admins can insert products" on public.products;
create policy "Admins can insert products" on public.products for insert to authenticated with check(exists(select 1 from public.admins a where lower(a.email)=lower(coalesce((select auth.jwt()->>'email'),''))));
drop policy if exists "Admins can update products" on public.products;
create policy "Admins can update products" on public.products for update to authenticated using(exists(select 1 from public.admins a where lower(a.email)=lower(coalesce((select auth.jwt()->>'email'),'')))) with check(exists(select 1 from public.admins a where lower(a.email)=lower(coalesce((select auth.jwt()->>'email'),''))));
drop policy if exists "Admins can delete products" on public.products;
create policy "Admins can delete products" on public.products for delete to authenticated using(exists(select 1 from public.admins a where lower(a.email)=lower(coalesce((select auth.jwt()->>'email'),''))));
drop policy if exists "Public can read active categories" on public.menu_categories;
create policy "Public can read active categories" on public.menu_categories for select to anon,authenticated using(active=true or exists(select 1 from public.admins a where lower(a.email)=lower(coalesce((select auth.jwt()->>'email'),''))));
drop policy if exists "Admins can insert categories" on public.menu_categories;
create policy "Admins can insert categories" on public.menu_categories for insert to authenticated with check(exists(select 1 from public.admins a where lower(a.email)=lower(coalesce((select auth.jwt()->>'email'),''))));
drop policy if exists "Admins can update categories" on public.menu_categories;
create policy "Admins can update categories" on public.menu_categories for update to authenticated using(exists(select 1 from public.admins a where lower(a.email)=lower(coalesce((select auth.jwt()->>'email'),'')))) with check(exists(select 1 from public.admins a where lower(a.email)=lower(coalesce((select auth.jwt()->>'email'),''))));
drop policy if exists "Admins can delete categories" on public.menu_categories;
create policy "Admins can delete categories" on public.menu_categories for delete to authenticated using(exists(select 1 from public.admins a where lower(a.email)=lower(coalesce((select auth.jwt()->>'email'),''))));
drop policy if exists "Admins can update menu settings" on public.menu_settings;
create policy "Admins can update menu settings" on public.menu_settings for update to authenticated using(exists(select 1 from public.admins a where lower(a.email)=lower(coalesce((select auth.jwt()->>'email'),'')))) with check(exists(select 1 from public.admins a where lower(a.email)=lower(coalesce((select auth.jwt()->>'email'),''))));
drop policy if exists "Admins can read orders" on public.orders;
create policy "Admins can read orders" on public.orders for select to authenticated using(exists(select 1 from public.admins a where lower(a.email)=lower(coalesce((select auth.jwt()->>'email'),''))));
drop policy if exists "Admins can update orders" on public.orders;
create policy "Admins can update orders" on public.orders for update to authenticated using(exists(select 1 from public.admins a where lower(a.email)=lower(coalesce((select auth.jwt()->>'email'),'')))) with check(exists(select 1 from public.admins a where lower(a.email)=lower(coalesce((select auth.jwt()->>'email'),''))));
drop policy if exists "Admins can read order items" on public.order_items;
create policy "Admins can read order items" on public.order_items for select to authenticated using(exists(select 1 from public.admins a where lower(a.email)=lower(coalesce((select auth.jwt()->>'email'),''))));