create extension if not exists pgcrypto;
create table if not exists public.products(id bigint generated by default as identity primary key,name text not null,slug text not null unique,description text not null default '',price numeric(12,2) not null check(price>=0),category text not null,icon text not null default '◻',active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists products_category_active_idx on public.products(category,active);
create table if not exists public.orders(id uuid primary key default gen_random_uuid(),customer_name text not null,customer_email text not null,status text not null default 'pending' check(status in('pending','paid','processing','shipped','completed','cancelled')),total numeric(12,2) not null default 0 check(total>=0),created_at timestamptz not null default now());
create table if not exists public.order_items(id bigint generated by default as identity primary key,order_id uuid not null references public.orders(id) on delete cascade,product_id bigint not null references public.products(id),quantity integer not null check(quantity>0),unit_price numeric(12,2) not null check(unit_price>=0));
create index if not exists order_items_order_id_idx on public.order_items(order_id);
create index if not exists order_items_product_id_idx on public.order_items(product_id);
create table if not exists public.contact_messages(id bigint generated by default as identity primary key,name text not null,email text not null,message text not null,created_at timestamptz not null default now());
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.contact_messages enable row level security;
drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products" on public.products for select to anon,authenticated using(active=true);
drop policy if exists "Public can submit contact messages" on public.contact_messages;
create policy "Public can submit contact messages" on public.contact_messages for insert to anon,authenticated with check(char_length(trim(name)) between 1 and 120 and char_length(trim(email)) between 3 and 320 and char_length(trim(message)) between 1 and 5000);
create or replace function public.place_order(p_customer_name text,p_customer_email text,p_items jsonb) returns uuid language plpgsql security definer set search_path=public,pg_catalog as $$
declare v_order_id uuid; v_total numeric(12,2);
begin
if char_length(trim(coalesce(p_customer_name,''))) not between 1 and 120 then raise exception 'Invalid customer name'; end if;
if char_length(trim(coalesce(p_customer_email,''))) not between 3 and 320 then raise exception 'Invalid customer email'; end if;
if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception 'Order must contain at least one item'; end if;
with requested as(select(item->>'id')::bigint product_id,greatest(1,least(99,(item->>'qty')::integer)) quantity from jsonb_array_elements(p_items)item)
select coalesce(sum(p.price*r.quantity),0) into v_total from requested r join public.products p on p.id=r.product_id where p.active=true;
if v_total<=0 then raise exception 'No valid products in order'; end if;
insert into public.orders(customer_name,customer_email,total)values(trim(p_customer_name),lower(trim(p_customer_email)),v_total)returning id into v_order_id;
insert into public.order_items(order_id,product_id,quantity,unit_price)
select v_order_id,r.product_id,r.quantity,p.price from(select(item->>'id')::bigint product_id,greatest(1,least(99,(item->>'qty')::integer)) quantity from jsonb_array_elements(p_items)item)r join public.products p on p.id=r.product_id where p.active=true;
return v_order_id;
end;$$;
revoke all on function public.place_order(text,text,jsonb) from public;
grant execute on function public.place_order(text,text,jsonb) to anon,authenticated;
insert into public.products(name,slug,description,price,category,icon)values
('Obsidian Watch','obsidian-watch','Minimal automatic watch with a brushed steel case and deep black dial.',189,'Accessories','◉'),
('Noir Headphones','noir-headphones','Wireless over-ear headphones designed around focused listening.',149,'Audio','◖◗'),
('Atlas Pack','atlas-pack','Structured everyday backpack with a clean silhouette and durable build.',119,'Everyday','▣'),
('Mono Lamp','mono-lamp','Architectural desk lamp with a warm, directional light.',89,'Home','◒'),
('Studio Camera','studio-camera','Compact creator camera concept for everyday visual work.',299,'Tech','▰'),
('Field Bottle','field-bottle','Double-wall steel bottle with a restrained matte finish.',39,'Everyday','◫'),
('Arc Keyboard','arc-keyboard','Low-profile mechanical keyboard with a precise, quiet feel.',129,'Tech','⌨'),
('Vector Mouse','vector-mouse','Ergonomic wireless mouse with a clean professional silhouette.',69,'Tech','◌'),
('Slate Wallet','slate-wallet','Slim everyday wallet cut for essential cards and cash.',59,'Accessories','▤'),
('Form Chair','form-chair','Sculptural lounge chair designed for long, comfortable sessions.',349,'Home','⌂'),
('Signal Speaker','signal-speaker','Compact wireless speaker with a balanced room-filling profile.',179,'Audio','◒'),
('Core Hoodie','core-hoodie','Heavyweight cotton hoodie with a clean, relaxed fit.',79,'Everyday','◇'),
('Grid Notebook','grid-notebook','Hardcover notebook built for ideas, plans, and daily notes.',24,'Everyday','▧'),
('Halo Desk Set','halo-desk-set','Minimal desk accessories designed to work as one visual system.',109,'Home','○'),
('Pulse Earbuds','pulse-earbuds','Compact wireless earbuds focused on clarity and everyday comfort.',99,'Audio','◍'),
('Frame Sunglasses','frame-sunglasses','Sharp acetate frames with a restrained, timeless profile.',74,'Accessories','◎'),
('Terra Mug','terra-mug','Hand-finished ceramic mug with a tactile matte surface.',32,'Home','∪'),
('Core SSD','core-ssd','Portable solid-state storage for creators and everyday workflows.',139,'Tech','▭')
on conflict(slug) do update set name=excluded.name,description=excluded.description,price=excluded.price,category=excluded.category,icon=excluded.icon,active=true,updated_at=now();
create or replace function public.set_updated_at() returns trigger language plpgsql set search_path=public,pg_catalog as $$begin new.updated_at=now();return new;end;$$;
drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at before update on public.products for each row execute function public.set_updated_at();